### ISSUE TITLE
Error: Cannot find module '<deltabot>/lib/server.js'

### ISSUE THREAD

**Issue by roastchicken** [MystK/delta-bot-three#70]
I recently tried running DeltaBot on my VPS because I wanted to see which issues were triggered depending on the circumstances of the comment (Giving a delta to OP, giving a delta to yourself, etc.). I have run the bot successfully before on this VPS, however this time (running the latest code from the repository) I got an error saying that it couldn't find module '\<deltabot>/lib/server.js' (<deltabot> being the location of the DeltaBot install).

I assumed I had done something wrong along the way and somehow messed up my install, so I decided to test on my computer. I already had a copy of the repository because I make commits from my computer (I'm too lazy to set up SSH keys on my VPS), so I pulled the new changes from the repository and went on to install (I guess technically I _built_ it). After getting over the hurdle of not `npm install`ing before trying to `npm start`, I ran into the same error.

Not being one to give up without a fight, I did a fresh install (build?) in another directory to eliminate any possibility of user error. Same error.

Here is the error in its entirety (from running on my Windows computer):

`Starting child process with 'node ./lib/server.js'
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\Julian\Desktop\deltabot\lib\server.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
 Program node ./lib/server.js exited with code 1`

On my VPS (Ubuntu) the line numbers are slightly different, although I assume this is due to differences in Linux and Windows node versions:

`Starting child process with 'node ./lib/server.js'
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/deltabot/delta-bot-three/lib/server.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
Program node ./lib/server.js exited with code 1`

If I have time tomorrow I will go through trying to run various versions of DeltaBot in hopes of finding the culprit commit.

**Comment by MystK** [comment]
Here's the PR that brought in the change.

We'll need to update the readme.

But basically you need to run, "npm run build"

https://github.com/MystK/delta-bot-three/pull/67/files

**Comment by roastchicken** [comment]
Ok, I added this step to the README in #71.

**Comment by MystK** [comment]
You need to run “npm run build” I think. A PR was brought in to precompile the source.

**Comment by roastchicken** [comment]
Is it just me or does anyone else just see two replies from @MystK in a row? Maybe I'm not seeing someone's comment.
